# This file provides overrides for manually building and using the PRODUCTION containers.
# - It REPLACES 'image' directives with 'build' directives
# - Sets the Docke build target to "prod"

services:
  web-api:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/web_api/Dockerfile
      target: prod

  noseyparker-scanner:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/noseyparker_scanner/Dockerfile
      target: prod

  dotnet-service:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/dotnet_service/Dockerfile
      target: prod

  file-enrichment:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/file_enrichment/Dockerfile
      target: prod

  file-enrichment-1:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/file_enrichment/Dockerfile
      target: prod

  file-enrichment-2:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/file_enrichment/Dockerfile
      target: prod

  file-enrichment-3:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/file_enrichment/Dockerfile
      target: prod

  frontend:
    image: !reset null
    build:
      context: ./projects/frontend/
      dockerfile: Dockerfile
      target: prod
    command: >
      sh -c "
        SECRET=\"$$HASURA_ADMIN_SECRET\" &&
        sed -i \"s/\\$$HASURA_ADMIN_SECRET/$$SECRET/g\" /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
      "
    labels:
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  jupyter:
    image: !reset null
    build:
      context: ./projects/jupyter/
      dockerfile: Dockerfile

  alerting:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/alerting/Dockerfile
      target: prod

  agents:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/agents/Dockerfile
      target: prod

  housekeeping:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/housekeeping/Dockerfile
      target: prod

  document-conversion:
    image: !reset null
    build:
      context: .
      dockerfile: ./projects/document_conversion/Dockerfile
      target: prod