apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: nemesis
requires:
  - configs: ["infra-core"]
  - configs: ["infra-nemesis"]
  - configs: ["monitoring"]
  - configs: ["services"]
  - configs: ["enrichment"]
---
#############################################################################
# infra-core - Deploys core infra (used by several services)
#  - Nginx ingress controller - API routes
#  - Elasticsearch/kibana - Used by Nemesis and Fluentd for logging
#############################################################################
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: infra-core
build:
  tagPolicy:
    inputDigest: {}
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0

manifests:
  rawYaml:
    - &k8s-elastic kubernetes/elastic/*

deploy:
  kubectl: {}

portForward:
  - &portForward-ingress
    resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 80
    localPort: 8080
    address: 0.0.0.0
  # - &portForward-elastic
  #   resourceType: service
  #   resourceName: nemesis-es-http
  #   namespace: default
  #   port: 9200
  #   localPort: 8834 # publicly expose elastic on 8834
  #   address: 0.0.0.0

---
#############################################################################
# monitoring - Monitoring infrastructure
#############################################################################
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: monitoring
build:
  tagPolicy:
    inputDigest: {}
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0

manifests:
  rawYaml:
    - &k8s-monitoring kubernetes/monitoring/*
    - &k8s-ingress-monitoring kubernetes/monitoring/ingress.yaml

deploy:
  kubectl: {}

---
#############################################################################
# infra-nemesis - Deploys static infrastructure (likely won't change during dev)
#############################################################################
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: infra-nemesis
build:
  tagPolicy:
    inputDigest: {}
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
  artifacts: []

manifests:
  rawYaml:
    # Static infra
    - &k8s-rabbitmq kubernetes/rabbitmq/*
    - &k8s-gotenberg kubernetes/gotenberg/*
    - &k8s-postgres kubernetes/postgres/*
    - &k8s-pgadmin kubernetes/pgadmin/*
    - &k8s-tika kubernetes/tika/*

deploy:
  kubectl: {}

portForward:
  - &portForward-minios
    resourceType: service
    resourceName: minio
    namespace: default
    port: 9001
    address: 0.0.0.0

# portForward:
#   - &portForward-postgres
#     resourceType: service
#     resourceName: postgres
#     namespace: default
#     port: 5432
#     localPort: 5432
#     address: 0.0.0.0
#   - &portForward-rabbmitmq-managementui
#     resourceType: service
#     resourceName: nemesis-rabbitmq-svc
#     namespace: default
#     port: 15672
#     localPort: 15672
#     address: 0.0.0.0
#   - &portForward-rabbmitmq-amqp
#     resourceType: service
#     resourceName: nemesis-rabbitmq-svc
#     namespace: default
#     port: 5672
#     localPort: 5672
#     address: 0.0.0.0
#   - &portForward-gotenberg
#     resourceType: service
#     resourceName: gotenberg
#     namespace: default
#     port: 3000
#     address: 0.0.0.0
#   - &portForward-tika
#     resourceType: service
#     resourceName: tika
#     namespace: default
#     port: 9998
#     address: 0.0.0.0

---
#########################################################################################
# nemesis-services - deploys API/enrichment services (common things that change during dev)
#########################################################################################
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: services
build:
  tagPolicy:
    inputDigest: {}
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - &build-dotnet
      image: nemesis-dotnet
      docker:
        dockerfile: dockerfiles/dotnet.Dockerfile
    - &build-nlp
      image: nemesis-nlp
      docker:
        dockerfile: dockerfiles/nlp.Dockerfile
    - &build-passwordcracker
      image: nemesis-passwordcracker
      docker:
        dockerfile: dockerfiles/passwordcracker.Dockerfile
    - &build-tensorflow-serving
      image: tensorflow-serving
      docker:
        dockerfile: dockerfiles/tensorflow-serving.Dockerfile

manifests:
  rawYaml:
    - &k8s-dotnet kubernetes/dotnet/*
    - &k8s-nlp kubernetes/nlp/*
    - &k8s-passwordcracker kubernetes/passwordcracker/*
    - &k8s-tensorflow-serving kubernetes/tensorflow-serving/*
deploy:
  kubectl: {}

# portForward:
#   - &portForward-dotnet
#     resourceType: service
#     resourceName: dotnet
#     namespace: default
#     port: 9800
#     address: 0.0.0.0
#   - &portForward-nlp
#     resourceType: service
#     resourceName: nlp
#     namespace: default
#     port: 9803
#     address: 0.0.0.0
#   - &portForward-tensorflow-serving
#     resourceType: service
#     resourceName: tensorflow-serving
#     namespace: default
#     port: 8501
#     address: 0.0.0.0
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: enrichment
build:
  tagPolicy:
    inputDigest: {}
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - &build-enrichment
      image: enrichment
      docker:
        dockerfile: dockerfiles/enrichment.Dockerfile
      sync:
        manual:
          - src: 'cmd/enrichment/**/*.py'
            dest: '/app/cmd/enrichment'
            strip: 'cmd/enrichment'

manifests:
  rawYaml:
    - &k8s-enrichment kubernetes/enrichment/*
deploy:
  kubectl: {}

# portForward:
#   - &portForward-dotnet
#     resourceType: service
#     resourceName: enrichment-webapi
#     namespace: default
#     port: 9910
#     address: 0.0.0.0
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: dashboard
build:
  tagPolicy:
    inputDigest: {}
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - &build-dashboard
      image: dashboard
      docker:
        dockerfile: dockerfiles/dashboard.Dockerfile
      sync:
        infer:
          - "**/*"

manifests:
  rawYaml:
    - &k8s-dashboard kubernetes/dashboard/*
deploy:
  kubectl: {}
