{{- if .Values.monitoring.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: {{ include "nemesis.namespace" . }}
  labels:
    {{- include "nemesis.labels" . | nindent 4 }}
    {{- include "nemesis.selectorLabels" (dict "name" "node-exporter" "context" .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nemesis.selectorLabels" (dict "name" "node-exporter" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nemesis.selectorLabels" (dict "name" "node-exporter" "context" .) | nindent 8 }}
      annotations:
        dapr.io/enabled: "false"
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: node-exporter
          image: "{{ .Values.monitoring.nodeExporter.image.repository }}:{{ .Values.monitoring.nodeExporter.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args:
            - "--path.procfs=/host/proc"
            - "--path.rootfs=/rootfs"
            - "--path.sysfs=/host/sys"
            - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
          ports:
            - containerPort: 9100
              name: metrics
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
          resources:
            {{- toYaml .Values.monitoring.nodeExporter.resources | nindent 12 }}
      tolerations:
        - operator: Exists
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: {{ include "nemesis.namespace" . }}
  labels:
    {{- include "nemesis.labels" . | nindent 4 }}
    {{- include "nemesis.selectorLabels" (dict "name" "node-exporter" "context" .) | nindent 4 }}
spec:
  selector:
    {{- include "nemesis.selectorLabels" (dict "name" "node-exporter" "context" .) | nindent 4 }}
  ports:
    - port: {{ .Values.monitoring.nodeExporter.port }}
      targetPort: metrics
      name: metrics
{{- end }}
