apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nemesis-secret-store
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: nemesis
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /dapr/secrets/secrets.json
