apiVersion: v1
kind: Secret
metadata:
  name: nemesis-secrets
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: nemesis
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "pgbouncer"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"
  S3_ACCESS_KEY: "${S3_ACCESS_KEY_VALUE}"
  S3_SECRET_KEY: "${S3_SECRET_KEY_VALUE}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  RABBITMQ_CONNECTION_STRING: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq.${NAMESPACE}.svc.cluster.local:5672"
  HASURA_ADMIN_SECRET: "${HASURA_ADMIN_SECRET}"
  BASIC_AUTH_USERS: "${BASIC_AUTH_USERS}"
  CHATBOT_DB_PASSWORD: "${CHATBOT_DB_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: nemesis-dapr-secrets
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: nemesis
type: Opaque
stringData:
  secrets.json: |
    {
      "HASURA_ADMIN_SECRET": "${HASURA_ADMIN_SECRET}",
      "RABBITMQ_USER": "${RABBITMQ_USER}",
      "RABBITMQ_PASSWORD": "${RABBITMQ_PASSWORD}",
      "RABBITMQ_CONNECTION_STRING": "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672",
      "POSTGRES_USER": "${POSTGRES_USER}",
      "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}",
      "POSTGRES_HOST": "pgbouncer",
      "POSTGRES_PORT": "${POSTGRES_PORT}",
      "POSTGRES_DB": "${POSTGRES_DB}",
      "POSTGRES_PARAMETERS": "${POSTGRES_PARAMETERS}",
      "S3_ACCESS_KEY": "${S3_ACCESS_KEY_VALUE}",
      "S3_SECRET_KEY": "${S3_SECRET_KEY_VALUE}",
      "BASIC_AUTH_USERS": "${BASIC_AUTH_USERS}",
      "CHATBOT_DB_PASSWORD": "${CHATBOT_DB_PASSWORD}"
    }
