{
 "title": "Nemesis Services",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "file-processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Seconds/Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sec/min" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"file-processor.default.svc.cluster.local:8000\", job=\"nemesis-services\"}[1m]))",
     "legendFormat": "sec/min"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(process_virtual_memory_bytes{instance=\"file-processor.default.svc.cluster.local:8000\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_file",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_file_sum[15m]) / rate(process_file_count[15m])",
     "legendFormat": "average time"
    }
   ]
  },
  {
   "title": "process_file_plaintext",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_file_plaintext_sum[15m]) / rate(process_file_plaintext_count[15m])",
     "legendFormat": "average time"
    }
   ]
  },
  {
   "title": "process_dotnet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_dotnet_sum[15m]) / rate(process_dotnet_count[15m])",
     "legendFormat": "average time"
    }
   ]
  },
  {
   "title": "extract_text",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(extract_text_sum[15m]) / rate(extract_text_count[15m])",
     "legendFormat": "average time"
    }
   ]
  },
  {
   "title": "convert_to_pdf",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(convert_to_pdf_sum[15m]) / rate(convert_to_pdf_count[15m])",
     "legendFormat": "average time"
    }
   ]
  },
  {
   "title": "extract_passwords",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(extract_passwords_sum[15m]) / rate(extract_passwords_count[15m])",
     "legendFormat": "average time"
    }
   ]
  },
  {
   "title": "dotnet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Seconds/Min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "sec/min" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=\"dotnet.default.svc.cluster.local:9801\", job=\"nemesis-services\"}[1m]))",
       "legendFormat": "sec/min"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(process_virtual_memory_bytes{instance=\"dotnet.default.svc.cluster.local:9801\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Processing",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(dotnet_service_process_sum[15m]) / rate(dotnet_service_process_count[15m])",
       "legendFormat": "average time"
      }
     ]
    },
    {
     "title": "Total Processing",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(dotnet_service_process_sum[15m]) / rate(dotnet_service_process_count[15m])",
       "legendFormat": "average time"
      }
     ]
    }
   ]
  },
  {
   "title": "es_connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Seconds/Min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "sec/min" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=\"es-connector.default.svc.cluster.local:8000\", job=\"nemesis-services\"}[1m]))",
       "legendFormat": "sec/min"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(process_virtual_memory_bytes{instance=\"es-connector.default.svc.cluster.local:8000\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "process_file_data_enriched",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_file_data_enriched_sum[15m]) / rate(process_file_data_enriched_count[15m])",
       "legendFormat": "average time"
      }
     ]
    },
    {
     "title": "process_file_data_plaintext",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_file_data_plaintext_sum[15m]) / rate(process_file_data_plaintext_count[15m])",
       "legendFormat": "average time"
      }
     ]
    }
   ]
  },
  {
   "title": "ml_models",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Seconds/Min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "sec/min" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=\"ml-models.default.svc.cluster.local:5001\", job=\"nemesis-services\"}[1m]))",
       "legendFormat": "sec/min"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(process_virtual_memory_bytes{instance=\"ml-models.default.svc.cluster.local:5001\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "process_document",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_document_sum[15m]) / rate(process_document_count[15m])",
       "legendFormat": "average time"
      }
     ]
    },
    {
     "title": "tokenize",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tokenize_sum[15m]) / rate(tokenize_count[15m])",
       "legendFormat": "average time"
      }
     ]
    },
    {
     "title": "extract_passwords_model",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(extract_passwords_model_sum[15m]) / rate(extract_passwords_model_count[15m])",
       "legendFormat": "average time"
      }
     ]
    },
    {
     "title": "extract_terms_regex",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(extract_terms_regex_sum[15m]) / rate(extract_terms_regex_count[15m])",
       "legendFormat": "average time"
      }
     ]
    }
   ]
  }
 ]
}