# hasura/metadata/databases.yaml
- name: default
  kind: postgres
  configuration:
    connection_info:
      use_prepared_statements: true
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed