{{- if .Values.aws }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  aws-bucket: {{ .Values.aws.bucket | quote }}
  aws-default-region: {{ .Values.aws.region | quote }}
  aws-kms-key-alias: {{ .Values.aws.kmsKeyAlias | quote }}
{{- end }}