---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  labels:
    app: dotnet
    component: enrichment-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  strategy: {}
  template:
    metadata:
      labels:
        app: dotnet
        component: enrichment-pipeline
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: operation-config
                  key: log-level
            - name: DATA_DOWNLOAD_DIR
              value: "/tmp"
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: operation-config
                  key: environment
            - name: PROMETHEUS_DISABLE_CREATED_SERIES
              value: "True"
            # - name: PROMETHEUS_PORT
            #   value: "9801"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.existingSecret }}
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.existingSecret }}
                  key: aws-secret-key
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws-bucket
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws-default-region
            - name: AWS_KMS_KEY_ALIAS
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws-kms-key-alias
            - name: ASSESSMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: operation-config
                  key: assessment-id
            - name: STORAGE_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: operation-config
                  key: storage_provider
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.existingSecret }}
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.existingSecret }}
                  key: root-password

          image: {{ .Values.dotnet.image.repository }}:{{ .Values.dotnet.image.tag }}
          imagePullPolicy: {{ .Values.dotnet.image.pullPolicy }}
          name: nemesis-dotnet
          ports:
            - containerPort: 9800
              name: dotnet-http
            # - containerPort: 9801
            #   name: dotnet-prom
          resources: {{ toYaml .Values.dotnet.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: dotnet-http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet
  labels:
    app: dotnet
    component: enrichment-pipeline
spec:
  type: {{ .Values.dotnet.service.type }}
  selector:
    app: dotnet
  ports:
    - port: {{ .Values.dotnet.service.port }}
      targetPort: 9800
      {{- if .Values.dashboard.service.nodePort }}
      nodePort: {{ .Values.dashboard.service.nodePort }}
      {{- end -}}