---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gotenberg
  name: gotenberg
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: {{ .Values.gotenberg.nodePort }}
  selector:
    app: gotenberg
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gotenberg-deny-all
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: gotenberg
  egress: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  labels:
    app: gotenberg
spec:
  # replicas: 2
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  strategy: {}
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - env:
            - name: DISABLE_GOOGLE_CHROME
              value: "1"
            # - name: DEFAULT_WAIT_TIMEOUT
            #   value: "60"
            # - name: MAXIMUM_WAIT_TIMEOUT
            #   value: "60"
          image: "{{ .Values.gotenberg.image.repository }}:{{ .Values.gotenberg.image.tag }}"
          imagePullPolicy: {{ .Values.gotenberg.image.pullPolicy }}
          name: gotenberg
          command: ["gotenberg", "--api-timeout=180s", "--libreoffice-restart-after=5", "--libreoffice-auto-start=true"]
          ports:
            - containerPort: 3000
              name: http
          resources: {{ toYaml .Values.gotenberg.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 5
      restartPolicy: Always