apiVersion: v1
kind: ConfigMap
metadata:
  name: noseyparker-rules
data:
  {{- $files := .Files.Glob "files/noseyparker/*.yaml" }}
  {{- if $files }}
  {{- range $path, $_ := $files }}
    {{ $path | base | trimSuffix ".yaml" | printf "%s.rules" }}: |
    {{- $.Files.Get $path | nindent 6 }}
  {{- end }}
  {{- else }}
    noseyparker.rules: |
      # Placeholder
  {{- end }}