---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  config_local.py: |
    # Allow email addresses that end with .local
    import email_validator
    email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("local")

  # pgpass: |
  #   postgres:5432:postgres:postgres:nemesis
  servers.json: |
    {
        "Servers": {
          "1": {
            "Name": "Nemesis",
            "Group": "Servers",
            "Port": 5432,
            "Username": "nemesis",
            "Host": "postgres",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
          }
        }
    }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  serviceName: pgadmin-service
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:7.7
          imagePullPolicy: IfNotPresent
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: pgadmin-email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: pgadmin-password
            - name: SCRIPT_NAME
              value: /pgadmin
            - name: MAX_LOGIN_ATTEMPTS
              value: "15"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: pgadmin-config
              mountPath: /pgadmin4/config_local.py
              subPath: config_local.py
              readOnly: true
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config
  volumeClaimTemplates:
    - metadata:
        name: pgadmin-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  selector:
    app: pgadmin
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: 80
      {{- if .Values.pgadmin.service.nodePort }}
      nodePort: {{ .Values.pgadmin.service.nodePort }}
      {{- end }}
---
# working for /pgadmin https://stackoverflow.com/a/72586264
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Values.basicAuth.middlewareName }}@kubernetescrd"
    {{- if .Values.pgadmin.ingress.annotations }}
    {{- .Values.pgadmin.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /pgadmin
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 80