apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: fileEnrichmentConfig
spec:
  # workflow:
  #   maxConcurrentWorkflowInvocations: 1
  #   maxConcurrentActivityInvocations: 1
  metric:
    enabled: true
    http:
      increasedCardinality: false