---
{{- $configmap := (lookup "v1" "ConfigMap" .Release.Namespace "operation-config") }}
{{- if $configmap }}
{{- $configData := index $configmap "data" }}
{{- $disableSlack := index $configData "disable-slack-alerting" }}
{{- if $disableSlack }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    {{- .Files.Get "files/alertmanager/config-dev.yaml" | nindent 4 }}
{{- else }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    {{- .Files.Get "files/alertmanager/config-prod.yaml" | nindent 4 }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
data:
  default.tmpl: |-
    {{- .Files.Get "files/alertmanager/default.tmpl" | nindent 4 }}
  slack.tmpl: |-
    {{- .Files.Get "files/alertmanager/slack.tmpl" | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      initContainers:
        - args:
            - sh
            - -c
            - cat /config.yml | envsubst > /etc/alertmanager/config.yml
          image: bhgedigital/envsubst
          imagePullPolicy: IfNotPresent
          name: envsubst
          env:
            - name: SLACK_ALERT_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: operation-config
                  key: slack-alert-channel
            - name: SLACK_WEB_HOOK
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.operation.existingSecret }}
                  key: slack-web-hook
          volumeMounts:
            - mountPath: /etc/alertmanager
              name: alertmanager
            - mountPath: /config.yml
              subPath: config.yml
              name: config-volume
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: "{{ .Values.alertmanager.image.pullPolicy }}"
          args:
            - "--config.file=/alertmanager/config.yml"
            - "--storage.path=/alertmanager"
          ports:
            - name: alertmanager
              containerPort: 9093
          resources: {{ toYaml .Values.alertmanager.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: templates-volume
              mountPath: /etc/alertmanager-templates
            - name: alertmanager
              mountPath: /alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: templates-volume
          configMap:
            name: alertmanager-templates
        - name: alertmanager
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
spec:
  type: {{ .Values.alertmanager.service.type }}
  selector:
    app: alertmanager
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: 9093
      {{- if .Values.alertmanager.service.nodePort }}
      nodePort: {{ .Values.alertmanager.service.nodePort }}
      {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: alertmanager-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /alertmanager
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-alertmanager-stripprefix@kubernetescrd, {{ .Values.nemesisNamespace }}-{{ .Values.auth.middlewareName }}@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /alertmanager
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: {{ .Values.alertmanager.service.port }}