apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
type: Opaque
data:
  username: {{ .Values.grafana.username | b64enc | quote }}

  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "grafana-creds") | default dict }}
  {{- $existingSecretData := (get $existingSecret "data") | default dict }}
  {{- $password := (get $existingSecretData "password") }}
  {{- if not $password}}
    {{- if .Values.grafana.password }}
      {{- $password = .Values.grafana.password | b64enc }}
    {{- else }}
      {{- $password = randAlphaNum 32 | b64enc }}
    {{- end }}
  {{- end }}
  password: {{ $password | quote }}