apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          imagePullPolicy: {{ .Values.nodeExporter.image.pullPolicy }}
          args:
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
            {{- if .Values.nodeExporter.useVolumeMounts }}
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            {{- end }}
          ports:
            - containerPort: 9100
              protocol: TCP
          {{- if .Values.nodeExporter.useVolumeMounts }}
          volumeMounts:
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
          {{- end }}
          resources: {{ toYaml .Values.nodeExporter.resources | nindent 12 }}
      volumes:
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /
          name: root
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  type: {{ .Values.nodeExporter.service.type }}
  ports:
    - port: {{ .Values.nodeExporter.service.port }}
      targetPort: 9100
      protocol: TCP
      {{- if .Values.nodeExporter.service.nodePort }}
      nodePort: {{ .Values.nodeExporter.service.nodePort }}
      {{- end }}