apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: nemesis
spec:
  version:  8.8.0
  auth:
    fileRealm:
      - secretName: elasticsearch-users
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        xpack.security.authc:
            anonymous:
              username: anonymous
              roles: superuser
              authz_exception: false
      podTemplate:
        spec:
          initContainers: # see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html#k8s-virtual-memory
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
            - name: volume-mount-hack
              image: busybox
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
              volumeMounts:
              - name: elasticsearch-data-volume
                mountPath: /usr/share/elasticsearch/data
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: "1000m"
                  memory: "1.5G"
                limits:
                  cpu: "2000m"
                  memory: "3G"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xmx1024m -Xms1024m"
              volumeMounts:
                - mountPath: /usr/share/elasticsearch/data
                  name: elasticsearch-data-volume
          restartPolicy: Always
          volumes:
            - name: elasticsearch-data-volume
              persistentVolumeClaim:
                claimName: elasticsearch-data-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  labels:
    type: local
    app: elasticsearch
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/elastic2/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-data-pvc
  labels:
    app: elasticsearch
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: elasticsearch-data-pv # the volume we want this claim to bind to


# # Comment the above and uncomment the following to have data wiped on each run,
# #   otherwise data is stored persistently
# apiVersion: elasticsearch.k8s.elastic.co/v1
# kind: Elasticsearch
# metadata:
#   name: nemesis
# spec:
#   version: 8.8.0
#   auth:
#     fileRealm:
#       - secretName: elasticsearch-users
#   http:
#     tls:
#       selfSignedCertificate:
#         disabled: true
#   nodeSets:
#     - name: default
#       count: 1
#       config:
#         xpack.security.authc:
#             anonymous:
#               username: anonymous
#               roles: superuser
#               authz_exception: false
#       podTemplate:
#         spec:
#           initContainers: # see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html#k8s-virtual-memory
#             - name: sysctl
#               securityContext:
#                 privileged: true
#                 runAsUser: 0
#               command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
#           containers:
#             - name: elasticsearch
#               resources: # Cranking down resource requirements for dev
#                 requests:
#                   cpu: "500m"
#                   memory: "1G"
#                 limits:
#                   cpu: "1000m"
#                   memory: "2G"
#               env:
#                 - name: ES_JAVA_OPTS
#                   value: "-Xmx512m -Xms512m"