apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: nemesis
spec:
  version: 8.8.0
  auth:
    fileRealm:
      - secretName: elasticsearch-users
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        xpack.security.authc:
            anonymous:
              username: anonymous
              roles: superuser
              authz_exception: false
      podTemplate:
        spec:
          initContainers: # see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html#k8s-virtual-memory
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources: # Cranking down resource requirements for dev
                requests:
                  cpu: "500m"
                  memory: "1G"
                limits:
                  cpu: "1000m"
                  memory: "2G"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xmx512m -Xms512m"