apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: file-enrichment-config
  namespace: {{ include "nemesis.namespace" . }}
  labels:
    {{- include "nemesis.labels" . | nindent 4 }}
spec:
  metric:
    enabled: true
    http:
      increasedCardinality: false
  {{- if .Values.monitoring.enabled }}
  tracing:
    expandParams: true
    samplingRate: "1"
    otel:
      protocol: grpc
      endpointAddress: "otel-collector:4317"
      isSecure: false
  {{- end }}
