apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nemesis-secret-store
  namespace: {{ include "nemesis.namespace" . }}
  labels:
    {{- include "nemesis.labels" . | nindent 4 }}
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /dapr/secrets/secrets.json
