apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  strategy: {}
  template:
    metadata:
      labels:
        app: tika
    spec:
      volumes:
        - name: tika-config
          configMap:
            name: tika-config
      containers:
        - env: []
          image: apache/tika:2.8.0.0-full
          imagePullPolicy: IfNotPresent
          name: tika
          # command: [ "/bin/sh", "-c", "exec java -cp \"/tika-server-standard-2.8.0.jar:/tika-extras/*\" org.apache.tika.server.core.TikaServerCli -h 0.0.0.0 -c /tika-config.xml"]
          # volumeMounts:
          #   - mountPath: /tika-config.xml
          #     subPath: tika-config.xml
          #     name: tika-config
          ports:
            - containerPort: 9998
              name: http
          resources: {}
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "200m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10

      restartPolicy: Always
status: {}
